name: Railway API Details

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download Railway JavaScript
        run: |
          curl -L -sS \
            "https://indianrail.gov.in/enquiry/js/SeatAvailability.js?version=9" \
            -o SeatAvailability.js

          echo "=== REQUEST DETAILS ==="

          grep -inE \
            "ajax|url:|type:|method:|data:|POST|GET|captcha|trainNo|sourceStation|destinationStation" \
            SeatAvailability.js | head -120
