name: Railway Form Details

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download Railway page
        run: |
          curl -L -sS \
            "https://indianrail.gov.in/enquiry/SEAT/SeatAvailability.html?locale=en" \
            -o railway.html

          echo "=== JAVASCRIPT / FORM SUBMIT DETAILS ==="

          grep -inE "captcha|seatavail|availability|ajax|submit|formData|api" railway.html | head -150
